### ISSUE TITLE
Unable to pull v1.40.5

### ISSUE THREAD

**Issue by alexgleason** [denoland/deno_docker#345]
In both GitLab CI and my development laptop, I am unable to pull the latest image:

```
➜  ditto git:(main) docker pull denoland/deno:1.40.5
Error response from daemon: manifest for denoland/deno:1.40.5 not found: manifest unknown: manifest unknown
➜  ditto git:(main) docker pull denoland/deno:1.40.4
1.40.4: Pulling from denoland/deno
31ad3619f756: Pull complete 
05217eb87ea3: Pull complete 
ef90dfccffd3: Pull complete 
c4e2ce20b06d: Pull complete 
ebac74c1f41a: Pull complete 
d354ccebdd17: Pull complete 
Digest: sha256:8e33911cd475a348fe799755a4267bc576e04bfc410f4edbd42469db035c0cd8
Status: Downloaded newer image for denoland/deno:1.40.4
docker.io/denoland/deno:1.40.4
➜  ditto git:(main) docker run -it denoland/deno:1.40.5 repl
Unable to find image 'denoland/deno:1.40.5' locally
docker: Error response from daemon: manifest for denoland/deno:1.40.5 not found: manifest unknown: manifest unknown.
See 'docker run --help'.
```

GitLab CI log: https://gitlab.com/soapbox-pub/ditto/-/jobs/6229114497

This is unusual, because normally I can just change the tag to upgrade. Did something change in this release?

**Comment by mmastrac** [comment]
I'm not sure why, but the 1.40.5 tag didn't push properly. 1.41.0 that we released yesterday should work properly.

**Comment by alexgleason** [comment]
I am still having the problem in the latest version:

```
ERROR: Job failed: failed to pull image "denoland/deno:v1.41.1" with specified policies [always]: Error response from daemon: manifest for denoland/deno:v1.41.1 not found: manifest unknown: manifest unknown (manager.go:237:0s)
```

See: https://gitlab.com/soapbox-pub/NSpec/-/jobs/6334185686
